### ISSUE TITLE
Convert a bulk of .png´s at once

### ISSUE THREAD

**Issue by katastrophe92** [dbconfig/png2ico#1]
Hello and thanks for this repository ☺. Does this work with multiple images at once? Hope someone can help me. Thanks!

Edit: I tried the drag and drop method but is not working sadly? First I installed Pillow then did the drag and drop thingy. Do I need to change something in the path or .bat file?

![WindowsTerminal 21-21-14 13April2023](https://user-images.githubusercontent.com/103950507/231859557-aac229e8-f4fe-4732-b74d-8a7a052770de.gif)

**Comment by dbconfig** [comment]
Hеllo 👋

> Does this work with multiple images at once?

if you mean whether the script can work with several different images at once (and output several different .ico files) - the answer is no, at the moment you need to work with each file separately)

> I tried the drag and drop method but is not working sadly? First I installed Pillow then did the drag and drop thingy. Do I need to change something in the path or .bat file?

The error is `Image size can't be larger than 255x255 pixels. Resize your image or use -r flag to continue.`
I just added the -r flag to `drag&drop.cmd` so now you can use it even with large PNGs.
